# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fish Properties
minecraft_version=1.6.4-MITE
yarn_mappings=1.6.4
loader_version=0.15.0

# Mod Properties
mod_version=1.0.2
mod_id=netmusic
mod_name=Net Music Mod
archives_base_name=netmusic

# Maven Properties
maven_group=com.github.MinecraftIsTooEasy
maven_id=netmusic

fabric_version=0.91.1+1.20.4

# Run Properties
username=Alex
screen_width=854
screen_height=480
